import {StyleSheet} from 'react-native';
import {COLORS, FONTS} from './../../constants/theme';
export const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.DEFAULT_WHITE,
  },
  text: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.DEFAULT_GREEN,
    margin: 10,
  },
  priceTagText: {
    color: COLORS.DEFAULT_WHITE,
    fontWeight: 'bold',
    fontSize: 18,
  },
  itemNameView: {
    marginLeft: 20,
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  fireImage: {
    height: 50,
    width: 50,
  },
  image: {
    width: '100%',
    height: 270,
  },
  fireImageView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingRight: 8,
  },
  mainView: {
    shadowColor: 'black',
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 6,
    shadowOpacity: 0.26,
    elevation: 2,
    backgroundColor: COLORS.DEFAULT_WHITE,
    paddingBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
    borderRadius: 10,
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 7,
    marginRight: 10,
    flex: 1,
    padding: 10,
    borderWidth: 1,
    borderColor: COLORS.transparent,
  },
  name: {
    fontSize: 24,
    color: COLORS.DEFAULT_BLACK,
  },
  header: {
    paddingHorizontal: 20,
    marginTop: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: 'red',
  },
  imageContainer: {
    flex: 0.45,
    marginTop: 30,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
  },
  Icon: {
    height: 30,
    width: 40,
    marginTop: 10,
    marginLeft: 10,
  },
  detailsContainer: {
    flex: 0.55,
    marginHorizontal: 7,
    marginBottom: 7,
    borderRadius: 20,
    marginTop: 30,
    paddingTop: 30,
  },
  line: {
    width: 25,
    height: 2,
    marginBottom: 5,
    marginRight: 3,
  },
  borderBtn: {
    borderColor: 'grey',
    borderWidth: 1,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    width: 60,
    height: 40,
  },
  borderBtnText: {
    fontWeight: 'bold',
    fontSize: 28,
  },
  pfcView: {
    flexDirection: 'row',
    paddingTop: 10,
  },
  buyBtn: {
    width: 150,
    height: 50,
    backgroundColor: COLORS.DEFAULT_GREEN,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  priceTag: {
    backgroundColor: COLORS.DEFAULT_YELLOW,
    width: 90,
    height: 40,
    justifyContent: 'center',
    borderTopLeftRadius: 25,
    borderBottomLeftRadius: 25,
    alignItems: 'center',
  },
  nutritionsText: {
    marginVertical: 5,
    fontSize: 18,
    marginLeft: 30,
    paddingTop: 3,
  },
  checkboxView: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: 10,
  },
  checkboxText: {
    marginLeft: 10,
    marginTop: 10,
    fontSize: 18,
    color: COLORS.DEFAULT_BLACK,
  },
  checkboxPrice: {
    marginLeft: 10,
    marginTop: 12,
    fontSize: 15,
    color: COLORS.DEFAULT_BLACK,
  },
  pfcText: {
    fontSize: 16,
    color: COLORS.DEFAULT_GREEN,
    paddingTop: 5,
  },
  icon1: {
    width: 40,
    height: 40,
  },
  nutritionText: {
    marginLeft: 20,
    marginTop: 10,
    fontSize: 20,
  },
  checkBoxTopView: {
    justifyContent: 'space-around',
  },
  innercheckBoxView: {
    flex: 1,
    flexDirection: 'row',
  },
  counterView: {
    alignItems: 'center',
    marginTop: 20,
    justifyContent: 'flex-end',
    backgroundColor: COLORS.DEFAULT_WHITE,
  },
  counterView2: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    justifyContent: 'space-evenly',
    backgroundColor: COLORS.DEFAULT_WHITE,
  },
  innerCounterView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  counterText: {
    fontSize: 20,
    fontWeight: 'bold',
    padding: 10,
  },
  addToCartText: {
    color: COLORS.DEFAULT_WHITE,
    fontSize: 18,
    fontWeight: 'bold',
  },
  pfcTopView: {
    width: '80%',
    paddingLeft: 5,
  },
  innermainView: {
    width: '25%',
    paddingLeft: 7,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginTop: 20,
  },
  modalView: {
    backgroundColor: COLORS.DEFAULT_WHITE,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: '100%',
    height: '50%',
  },
  button: {
    borderRadius: 10,
    padding: 12,
    elevation: 1,
  },
  buttonClose: {
    backgroundColor: COLORS.DEFAULT_GREEN,
  },
  saveButton: {
    margin: 20,
  },
  textStyle: {
    color: COLORS.DEFAULT_WHITE,
    textAlign: 'center',
    fontSize: 18,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
  },
  modalText: {
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'center',
    color: COLORS.DEFAULT_BLACK,
  },
  modalIcon: {},
  modelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '80%',
  },
  center: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  nutritionHeading: {
    fontSize: 20,
    textAlign: 'center',
    color: COLORS.DEFAULT_BLACK,
  },
  nutritionContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
    paddingTop: 10,
  },
  gramsText: {
    fontSize: 22,
    fontWeight: 'bold',
    color: COLORS.black,
  },
  descContainer: {
    padding: 10,
    marginLeft: 10,
  },
  descText: {
    fontSize: 16,
  },
});
