
import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
    input: {
      height: 40,
      marginLeft: 200,
      bottom: 30,
      right: 5,
      borderWidth: 1,
      padding: 10,
    },
    input1: {
      height: 40,
      marginLeft: 20,
      bottom: 30,
      borderWidth: 0.5,
      padding: 10,
    },
    button: {
      alignItems: 'center',
      backgroundColor: "#841584",
      paddingLeft: 0,
      borderRadius: 15,
      height: 30,
      justifyContent: "center",
      width: 100,
      left: 280,
      top: 30,
    },
    button1: {
      alignItems: 'center',
      backgroundColor: "#841584",
      width: 100,
      justifyContent: "center",
      left: 280,
      bottom: 20,
      top: 50,
      height:40,
      borderRadius: 15,
    },
    button2: {
      alignItems: 'center',
      backgroundColor: "#841584",
      borderRadius: 15,
      justifyContent: "center",
      paddingLeft: 0,
      height: 40,
      width: 100,
      left: 20,
      top: 90,
    },
  });